### ISSUE TITLE
Package Incompatible w/ Laravel 7

### ISSUE THREAD

**Issue by dp88** [stechstudio/logging#4]
The dependency on `illuminate/log` `^6.0` is preventing projects using this package from upgrading to Laravel 7. Hopefully the only change necessary is to `composer.json`.

```
stechstudio/logging 2.0.0 requires illuminate/log ^6.0 -> satisfiable by laravel/framework[v6.16.0], illuminate/log[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0,
 v6.8.0]
```

**Comment by bubba-h57** [comment]
https://github.com/stechstudio/logging/commit/0d16c04690598fce8a9153a2a2802e20881cce4e to bump the version.
